#!/bin/bash

CC = g++ -std=c++17
CFLAGS = -pedantic-errors -Wall -Wextra -rdynamic -L./pnp/ -Wl,-rpath,./pnp/
RELEASE = -DNDEBUG -O3
DEBUG = -g
INCLUDE = -I./include -I../include
OBJ = src/i_task.o src/i_re_task.o src/thread_pool.o src/pnp.o
TARGET = re_fw.out


$(TARGET): $(OBJ) 
	$(CC) $(INCLUDE) -o $(TARGET) $(CFLAGS) $(OBJ)

%.o: %.cpp $(DEPS)
	$(CC) -c -o $@  $< $(INCLUDE) $(CFLAGS) 

all: clean
all: $(TARGET)

debug: CFLAGS += $(DEBUG)
debug: $(OBJ)
	$(CC) $(CFLAGS) $^ -o $(TARGET)

release: CFLAGS += $(RELEASE)
release: $(OBJ)
	$(CC) $(CFLAGS) $^ -o $(TARGET)

clean:
	rm -f $(OBJ) *.out core.*

