#!/bin/bash 

g++ -std=c++11 -c -fpic -I. singleton_test_so.cpp

g++ -std=c++11 -shared singleton_test_so.o -o libsingleton.so 

g++ -std=c++11 singleton_test.cpp -o test_so.out -L. -Wl,-rpath,. -lsingleton 

rm singleton_test_so.o
